- name: update packages
  apt: name=memcached state=present

- name: setup config file
  template: src=../templates/conf.j2 dest=/etc/memcached.conf

- name: start service and enable at boot
  service: name=memcached enabled=yes state=started
