---
# This playbook provisions a local dev vagrant

- name: invoke all the roles necessary for a local dev vagrant
  hosts: vagrant
  remote_user: "{{ deploy_user }}"
  sudo: yes
  roles:
    - common
    - node
    - postgres
    - rambler
    - memcached_local_install
    - autotrack
