---
# Default variables for the rambler role

rambler_local_go: "/home/{{ deploy_user }}/go"
rambler_go_root: /usr/lib/go
rambler_go_bin: "{{ rambler_local_go }}/bin"
rambler_go_path: "{{ rambler_local_go }}"
rambler_package_name: "github.com/rsterbin/rambler"
rambler_repo: "https://{{ rambler_package_name }}.git"
rambler_script_location: /usr/local/bin
